#!/bin/bash 

. utils.sh

set_namespace $CONJUR_NAMESPACE_NAME

CONJUR_MASTER_ROUTE=$($cli get routes | grep conjur-master | awk '{ print $2 }')
CONJUR_MASTER_URL="https://$CONJUR_MASTER_ROUTE"
DEMO_CLIENT=demo-client

echo "Starting demo container..."
docker run \
  -v $(pwd)/demo:/demo \
  --entrypoint sh \
  --name $DEMO_CLIENT \
  --env CONJUR_MASTER_URL=$CONJUR_MASTER_URL \
  --env CONJUR_ACCOUNT=$CONJUR_ACCOUNT \
  cyberark/conjur-cli:4-latest \
  -c "sleep infinity" &
sleep 2
clear
echo "cd to /demo and run scripts in sequence"
docker exec -it $DEMO_CLIENT bash
echo "Deleting demo container..."
docker stop $DEMO_CLIENT
sleep 2
docker rm $DEMO_CLIENT
