#!/bin/bash
DEMO_CLIENT=demo-client
OPENSHIFT_IP=$(minishift ip)
MASTER_NODE_PORT=30443
FOLLOWER_NODE_PORT=30444

echo "Starting demo container..."
docker run \
  -v $(pwd)/demo:/demo \
  --entrypoint sh \
  --name $DEMO_CLIENT \
  --env OPENSHIFT_IP=$OPENSHIFT_IP \
  --env MASTER_NODE_PORT=$MASTER_NODE_PORT \
  --env FOLLOWER_NODE_PORT=$FOLLOWER_NODE_PORT \
  --env CONJUR_ACCOUNT=$CONJUR_ACCOUNT \
  cyberark/conjur-cli:4-latest \
  -c "sleep infinity" &
sleep 2
clear
echo "cd to /demo and run scripts in sequence"
docker exec -it $DEMO_CLIENT bash
echo "Deleting demo container..."
docker stop $DEMO_CLIENT
sleep 2
docker rm $DEMO_CLIENT
